### Pull company from Airtable and push to MongoDB

POST {{host}}/v1/integrations/airtable/pull_companies


### Happy path push comany to Airtable

POST {{host}}/v1/integrations/sync/deal
Content-Type: application/json

{
  "user_email": "vladimir@ingainer.pro",
  "startup": {
    "name": "Careerflow",
    "website": "https://careerflow.ai",
    "foundation_year": "Unknown"
  },
  "features": {
    "Product Type": {
      "value": [
        "Educational Service"
      ],
      "source": [
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Provides contextual actions, insights, and recommendations\"",
          "value": "pitch_deck/page=3"
        }
      ],
      "criterion": "Product Type"
    },
    "Customer Type": {
      "value": [
        "Consumer"
      ],
      "source": [
        {
          "page": "9",
          "type": "pitch_deck",
          "quote": "\"There are 63M white-collared workers in the US alone\"",
          "value": "pitch_deck/page=9"
        },
        {
          "page": "9",
          "type": "pitch_deck",
          "quote": "\"Premium Subscription\"",
          "value": "pitch_deck/page=9"
        }
      ],
      "criterion": "Customer Type"
    },
    "Business Model": {
      "value": "Careerflow operates a digital platform, including a Chrome Extension and Web app, aimed at simplifying the job search for individual consumers, primarily white-collared workers in the U.S., generating revenue through premium subscriptions and value-added services, and utilizes a mixed distribution strategy of direct engagement and B2B2C partnerships.",
      "source": [],
      "criterion": "Business Model"
    },
    "Problem Statement": {
      "value": "Job searching is one of the most stressful experiences for individuals, as indicated by 73% of people.",
      "source": [
        {
          "page": "2",
          "type": "pitch_deck",
          "quote": "\"73% of people say job search is one of the most stressful things in their lives\"",
          "value": "pitch_deck/page=2"
        },
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Provides contextual actions, insights, and recommendations\"",
          "value": "pitch_deck/page=3"
        }
      ],
      "criterion": "Problem Statement"
    },
    "Revenue Model Type": {
      "value": [
        "Subscription",
        "Service fees"
      ],
      "source": [
        {
          "page": "9",
          "type": "pitch_deck",
          "quote": "\"Premium Subscription\"",
          "value": "pitch_deck/page=9"
        },
        {
          "page": "9",
          "type": "pitch_deck",
          "quote": "\"Value Added Services\"",
          "value": "pitch_deck/page=9"
        }
      ],
      "criterion": "Revenue Model Type"
    },
    "Solution Statement": {
      "value": "Careerflow simplifies the job search process through a digital platform that provides contextual actions, insights, and recommendations.",
      "source": [
        {
          "page": "2",
          "type": "pitch_deck",
          "quote": "\"73% of people say job search is one of the most stressful things in their lives\"",
          "value": "pitch_deck/page=2"
        },
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Provides contextual actions, insights, and recommendations\"",
          "value": "pitch_deck/page=3"
        }
      ],
      "criterion": "Solution Statement"
    },
    "Distribution Strategy": {
      "value": [
        "Direct",
        "B2B2C"
      ],
      "source": [
        {
          "page": "10",
          "type": "pitch_deck",
          "quote": "\"Organic / Content Led (100K+ social media followers)\"",
          "value": "pitch_deck/page=10"
        },
        {
          "page": "10",
          "type": "pitch_deck",
          "quote": "\"Privileged access via partnerships\"",
          "value": "pitch_deck/page=10"
        }
      ],
      "criterion": "Distribution Strategy"
    },
    "Product Structure Type": {
      "value": [
        "Single product"
      ],
      "source": [
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Provides contextual actions, insights, and recommendations\"",
          "value": "pitch_deck/page=3"
        },
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Currently focused on job search\"",
          "value": "pitch_deck/page=3"
        },
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Provides contextual actions, insights, and recommendations\"",
          "value": "pitch_deck/page=3"
        },
        {
          "page": "3",
          "type": "pitch_deck",
          "quote": "\"Available as a Chrome Extension + Web app\"",
          "value": "pitch_deck/page=3"
        }
      ],
      "criterion": "Product Structure Type"
    },
    "Deal Size": {
      "value": [
        "Unknown"
      ],
      "source": [
        {
          "page": "11",
          "type": "pitch_deck",
          "quote": "\"We are raising pre-seed.\"",
          "value": "pitch_deck/page=11"
        }
      ],
      "criterion": "Deal Size"
    }
  },
  "people": [
    {
      "name": "Nikita Gupta",
      "linkedin_url": "https://www.linkedin.com/in/guptanikita16",
      "features": {
        "Founder Name": {
          "value": "Nikita Gupta",
          "source": [],
          "criterion": "Founder Name"
        },
        "founder_role": {
          "value": "COO",
          "source": [],
          "criterion": "founder_role"
        },
        "linkedin_url": {
          "value": "https://www.linkedin.com/in/guptanikita16",
          "source": [],
          "criterion": "linkedin_url"
        },
        "Repeat Founder": {
          "value": false,
          "source": [],
          "criterion": "Repeat Founder"
        },
        "Founder Summary": {
          "value": "Nikita Gupta is a seasoned COO with a strong background in technical recruitment, having worked with top-tier companies like Uber and Amazon Web Services. She holds a Master's degree in IT in Business Analytics from Singapore Management University and a Bachelor's in Computer Science from Jaypee Institute of Information Technology. As a recognized Career Influencer with a substantial following, Gupta has co-founded Careerflow.ai, which has gained notable media attention and is backed by prestigious accelerators like Techstars. She also possesses certifications in Marketing Foundations from The Trade Desk and SEMrush Site Audit.",
          "source": [],
          "criterion": "Founder Summary"
        },
        "Strong Education": {
          "value": false,
          "source": [],
          "criterion": "Strong Education"
        }
      }
    }
  ],
  "sources": []
}