name: 'Setup Python Environment'
description: 'Checks out repo, sets up Python, and installs dependencies'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'