name: dvc-agent
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: .venv
description: Synapse Backend
config:
  gcp:project: dvc-agent
  pulumi:tags:
    value:
      pulumi:template: gcp-python
