name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Test and Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-python
    - name: Cloud SDK Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{secrets.SERVICE_ACCOUNT}}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Run CI
      run: make ci